# Bithumb exchange configuration
bithumb:
  enabled: true

  # Request configuration
  request:
    # API endpoint configuration
    api_url: "https://feed.bithumb.com/_next/data/{navigation_id}/notice.json"
    method: get
    header_profile: browser_chrome
    proxy_pool: proxyseller_isp
    rate_limit_profile: strict

    # Exchange-specific header overrides/additions
    headers_override:
      referer: "https://feed.bithumb.com/"
      accept: "application/json"

    # Default parameters for this exchange
    kwargs:
      params:
        category: ''
        page: '1'

  # Monitoring configuration
  monitoring:
    poll_interval: 3  # seconds
    navigation_id_refresh: 3600  # refresh navigation_id every hour

  patterns: [
    '\w+\(([ A-Z0-9 ]+)\)',

    #    '\(([ A-Z0-9 ]+)\) 원화 마켓 추가',
#    '([ A-Z0-9 ]+(?:,\s*[ A-Z0-9 ]+)*) 원화 마켓'
  ]

  categories:
    - original_ids: ["거래유의"]
      show_name: "Transaction Caution"
      internal_name: "other"
    - original_ids: ["거래지원종료"]
      show_name: "Delisting"
      internal_name: "delisting"
    - original_ids: ["공시", "안내"]
      show_name: "Announcements"
      internal_name: "news"
    - original_ids: ["마켓 추가"]
      show_name: "Market Addition"
      internal_name: "listing_spot"
    - original_ids: ["신규서비스"]
      show_name: "New Service"
      internal_name: "other"
    - original_ids: ["업데이트"]
      show_name: "Update"
      internal_name: "other"
    - original_ids: ["이벤트"]
      show_name: "Activities"
      internal_name: "activities"
    - original_ids: ["입출금", "점검"]
      show_name: "Maintenance"
      internal_name: "maintenance"