bybit:
  enabled: true

  request:
    api_url: "https://announcements.bybit.com/x-api/announcements/api/search/v1/index/announcement-posts_en"
    method: post
    header_profile: browser_chrome
    proxy_pool: proxyseller_isp
    rate_limit_profile: strict
    headers_override: {}
    kwargs:
      'data': {
          'query': '',
          'page': 0,
          'hitsPerPage': 20,
      }

  monitoring:
    poll_interval: 3
    navigation_id_refresh: 3600

  patterns: [
    'New Listing : ([A-Z0-9]+USDT) Perpetual Contract',
    '([A-Z0-9]+USDT) Perpetual Contract Moved',
    'Migration of ([A-Z0-9]+USDT(?:,\s*[A-Z0-9]+USDT)*)',
    '([A-Z0-9]+)USDT Perpetual',
    '([A-Z0-9]+) at all-time high',
    'Listing of ([A-Z0-9]+) on Convert',
  ]

  categories:
    - original_ids: ["New Listings"]
      show_name: "New Listings"
      internal_name: "listing_spot"
    - original_ids: ["Latest Activities", "Weekly Updates", "Web3"]
      show_name: "Activities"
      internal_name: "activities"
    - original_ids: ["Delistings"]
      show_name: "Delistings"
      internal_name: "delisting"
    - original_ids: ["Latest Bybit News"]
      show_name: "News"
      internal_name: "news"
    - original_ids: ["Maintenance Updates"]
      show_name: "Maintenance"
      internal_name: "maintenance"
    - original_ids: ["Partnership Announcement", "Listing Billboard", "More"]
      show_name: "Other"
      internal_name: "other"