kucoin:
  enabled: true

  request:
    api_url: 'https://www.kucoin.com/_api/cms/articles'
    method: get
    header_profile: browser_chrome
    proxy_pool: proxyseller_isp
    rate_limit_profile: strict
    headers_override: {}
    kwargs:
      params:
        page: '1'
        pageSize: '1'

  monitoring:
    poll_interval: 3
    navigation_id_refresh: 3600
    
  patterns: [
    '([A-Z0-9]+) \(([A-Z0-9]+)\) Gets Listed',
    'KuCoin Futures New Listing: ([A-Z0-9]+USDT) Perpetual Contract',
    'KuCoin to Add ([A-Z0-9]+(?:/| and )[A-Z0-9]+) Trading Pair',
    '([A-Z0-9]+) \(([A-Z0-9]+)\) Listing Campaign',
    '([A-Z0-9]+) Distribution for ([A-Z0-9]+) Holders',
    '([A-Z0-9]+) Team Completes',
    'Introducing the ([A-Z0-9]+) Points Program',
    'USD⓸-Margined ([A-Z0-9]+USDTM(?:、[A-Z0-9]+USDTM)*)',
    'Will Delist the ([A-Z0-9]+USDT(?: and [A-Z0-9]+USDT)*) Perpetual Contracts',
    'Will Delist the ([A-Z0-9]+USDT) Perpetual Contract',
    'Will Delist the ([A-Z0-9]+USDT(?:,\s*[A-Z0-9]+USDT)* and [A-Z0-9]+USDT) Perpetual Contracts',
    'Closed the Deposit Service of ([A-Z0-9]+) \(([A-Z0-9]+)\)',
    '[A-Za-z0-9]+ \(([A-Z0-9]+)\)',
    'CandyBomb x ([A-Z0-9]+):',
    'of ([A-Z0-9]+)'
  ]

  categories:
    - original_ids: ['Latest Events', 'Web3']
      show_name: 'Activities'
      internal_name: 'activities'
    - original_ids: ['New Listings']
      show_name: 'New Listings'
      internal_name: 'listing_spot'
    - original_ids: ['Latest Announcements', 'Product Updates', 'Institutions and VIPs', 'Others']
      show_name: 'Other'
      internal_name: 'other'
    - original_ids: ['System Maintenance']
      show_name: 'Maintenance'
      internal_name: 'maintenance'
    - original_ids: ['Delisting']
      show_name: 'Delisting'
      internal_name: 'delisting'