upbit:
  enabled: true

  request:
    api_url: 'https://api-manager.upbit.com/api/v1/announcements'
    method: get
    header_profile: browser_chrome
    proxy_pool: proxyseller_isp
    rate_limit_profile: strict
    headers_override: {}
#      referer: 'https://upbit.com/'
    kwargs:
      params:
        os: 'web'
        page: '1'
        per_page: '5'
        category: 'all'

  monitoring:
    poll_interval: 5
    navigation_id_refresh: 3600

  patterns: [
    '\w+\(([ A-Z0-9 ]+)\)',
    '([A-Za-z0-9]+) \([A-Z0-9]+\)'
    #    '([ A-Z0-9 ]+)\(([ A-Z0-9 ]+)\) \(KRW',
#    'for ([ A-Z0-9 ]+)\(([ A-Z0-9 ]+)\)',
#    'Support for ([ A-Z0-9 ]+) \(',
#    'Termination of Trading Support for ([ A-Z0-9 ]+) \(',
#    'Investment Warning \(([ A-Z0-9 ]+)\)'
  ]

  categories:
    - original_ids: ['All']
      show_name: 'All'
      internal_name: 'other'
    - original_ids: ['Notice']
      show_name: 'Notice'
      internal_name: 'other'
    - original_ids: ['Trade']
      show_name: 'Trade'
      internal_name: 'listing_spot'
    - original_ids: ['D/W']
      show_name: 'D/W'
      internal_name: 'delisting'
    - original_ids: ['Maintenance']
      show_name: 'Maintenance'
      internal_name: 'maintenance'
    - original_ids: ['Digital Asset']
      show_name: 'Digital Asset'
      internal_name: 'other'
    - original_ids: ['NFT']
      show_name: 'NFT'
      internal_name: 'activities'
    - original_ids: ['Service+']
      show_name: 'Service+'
      internal_name: 'other'
    - original_ids: ['Event']
      show_name: 'Event'
      internal_name: 'activities'