# Reusable header profiles
profiles:
  no_header:

  basic:
    User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    Connection: "keep-alive"

  browser_chrome:
    User-Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36'
    accept: "*/*"
    accept-language: "en-US,en;q=0.9"
    sec-ch-ua: '"Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"'
    sec-ch-ua-mobile: "?0"
    sec-ch-ua-platform: '"Windows"'
    sec-fetch-dest: "empty"
    sec-fetch-mode: "cors"
    sec-fetch-site: "same-origin"
    Connection: "keep-alive"

  api_json:
    Content-Type: "application/json"
    Accept: "application/json"