# Rate limiting profiles
profiles:
  strict:
    requests_per_second: 1
    burst_size: 3
    cooldown_seconds: 60

  moderate:
    requests_per_second: 5
    burst_size: 10
    cooldown_seconds: 30

  relaxed:
    requests_per_second: 10
    burst_size: 20
    cooldown_seconds: 10